# Generated by Django 2.0.2 on 2018-02-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MakeAnAppointment',
            new_name='Appointment',
        ),
        migrations.RenameModel(
            old_name='CheckYourEligibility',
            new_name='Eligibility',
        ),
        migrations.RemoveField(
            model_name='education',
            name='applieduser',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='applieduser',
        ),
        migrations.RemoveField(
            model_name='fileuploads',
            name='applieduser',
        ),
        migrations.RemoveField(
            model_name='mailingaddress',
            name='applieduser',
        ),
        migrations.DeleteModel(
            name='OtherInformation',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='applieduser',
        ),
        migrations.DeleteModel(
            name='AppliedUser',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Employment',
        ),
        migrations.DeleteModel(
            name='FileUploads',
        ),
        migrations.DeleteModel(
            name='MailingAddress',
        ),
        migrations.DeleteModel(
            name='Tests',
        ),
    ]
