# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_applieduser_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applieduser',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applieduser',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='mobile_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='telephone_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='gmat',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='gre',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ielts',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='phone',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='pte',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='sat',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='toefl',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
