# Generated by Django 2.0.2 on 2018-02-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180213_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
