# Generated by Django 2.0.2 on 2018-02-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='unique_code',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
