# Generated by Django 2.0.2 on 2018-02-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='unique_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
