# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180324_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'verbose_name': 'AuthUser'},
        ),
        migrations.AddField(
            model_name='event',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Branch'),
            preserve_default=False,
        ),
    ]
