# Generated by Django 2.0.2 on 2018-02-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1000)),
                ('address', models.TextField()),
                ('telephone_no', models.PositiveIntegerField()),
                ('mobile_no', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('purpose_of_visit', models.CharField(max_length=100)),
                ('evidence_of_id', models.CharField(max_length=100)),
                ('evidence_of_id_number', models.CharField(max_length=100)),
                ('appointment', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone', models.PositiveIntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('ielts', models.PositiveIntegerField()),
                ('toefl', models.PositiveIntegerField()),
                ('sat', models.PositiveIntegerField()),
                ('gre', models.PositiveIntegerField()),
                ('gmat', models.PositiveIntegerField()),
                ('pte', models.PositiveIntegerField()),
                ('priority_country', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
