# Generated by Django 2.0.2 on 2018-02-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_auto_20180218_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applieduser',
            name='gmat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applieduser',
            name='gre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applieduser',
            name='ielts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applieduser',
            name='pte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applieduser',
            name='sat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applieduser',
            name='toefl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
