# Generated by Django 2.0.2 on 2018-02-18 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0005_auto_20180218_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='applieduser',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
